// State × category credential requirements for the Gibens pro onboarding flow.
// If a (state, category) pair is absent, no state-level license is required
// for that trade in that state — local permits may still apply.

export const US_STATES = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'DC', name: 'Washington D.C.' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
]

export type LicenseInfo = {
  authority: string
  licenseType: string
  note?: string
}

// State → category slug → license info (null = no state license, check local)
export const STATE_LICENSE_INFO: Record<string, Partial<Record<string, LicenseInfo | null>>> = {
  AL: {
    electrician:      { authority: 'Alabama Electrical Contractors Board', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Alabama Plumbers & Gas Fitters Examining Board', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Alabama Licensing Board for General Contractors', licenseType: 'Mechanical Contractor License' },
    pest_control:     { authority: 'Alabama Department of Agriculture & Industries', licenseType: 'Commercial Pesticide Applicator License' },
    security_systems: { authority: 'Alabama Electronic Security Board of Licensure', licenseType: 'Electronic Security License' },
    locksmith:        { authority: 'Alabama Electronic Security Board of Licensure', licenseType: 'Locksmith License' },
    roofing:          { authority: 'Alabama Licensing Board for General Contractors', licenseType: 'General Contractor License' },
  },
  AK: {
    electrician:      { authority: 'Alaska Department of Labor and Workforce Development', licenseType: 'Electrical Administrator License' },
    plumber:          { authority: 'Alaska Department of Labor and Workforce Development', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Alaska Department of Labor and Workforce Development', licenseType: 'Mechanical Administrator License' },
    pest_control:     { authority: 'Alaska Department of Environmental Conservation', licenseType: 'Pesticide Applicator License' },
    security_systems: { authority: 'Alaska Department of Public Safety', licenseType: 'Alarm System Contractor License' },
    roofing:          { authority: 'Alaska Department of Commerce', licenseType: 'General Contractor License' },
  },
  AZ: {
    electrician:      { authority: 'Arizona Registrar of Contractors', licenseType: 'C-11 Electrical Contractor License' },
    plumber:          { authority: 'Arizona Registrar of Contractors', licenseType: 'CR-37 Plumbing Contractor License' },
    hvac:             { authority: 'Arizona Registrar of Contractors', licenseType: 'CR-39 HVAC Contractor License' },
    pest_control:     { authority: 'Arizona Department of Agriculture', licenseType: 'Pest Management License' },
    security_systems: { authority: 'Arizona Department of Public Safety', licenseType: 'Alarm System Contractor License' },
    locksmith:        { authority: 'Arizona Department of Public Safety', licenseType: 'Locksmith License' },
    roofing:          { authority: 'Arizona Registrar of Contractors', licenseType: 'CR-90 Roofing Contractor License' },
    pool_service:     { authority: 'Arizona Registrar of Contractors', licenseType: 'CR-3 Swimming Pool Contractor License' },
  },
  AR: {
    electrician:      { authority: 'Arkansas State Board of Electrical Examiners', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Arkansas State Board of Health', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Arkansas Contractors Licensing Board', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Arkansas State Plant Board', licenseType: 'Pest Control Business License' },
    security_systems: { authority: 'Arkansas Alarm System Licensing Board', licenseType: 'Alarm System Contractor License' },
    roofing:          { authority: 'Arkansas Contractors Licensing Board', licenseType: 'General Contractor License' },
  },
  CA: {
    electrician:      { authority: 'California Contractors State License Board (CSLB)', licenseType: 'C-10 Electrical Contractor License' },
    plumber:          { authority: 'California Contractors State License Board (CSLB)', licenseType: 'C-36 Plumbing Contractor License' },
    hvac:             { authority: 'California Contractors State License Board (CSLB)', licenseType: 'C-20 HVAC Contractor License' },
    pest_control:     { authority: 'California Department of Pesticide Regulation', licenseType: 'Structural Pest Control License' },
    security_systems: { authority: 'California Bureau of Security and Investigative Services (BSIS)', licenseType: 'Alarm Company Operator License' },
    locksmith:        { authority: 'California Bureau of Security and Investigative Services (BSIS)', licenseType: 'Locksmith License' },
    roofing:          { authority: 'California Contractors State License Board (CSLB)', licenseType: 'C-39 Roofing Contractor License' },
    pool_service:     { authority: 'California Contractors State License Board (CSLB)', licenseType: 'C-53 Swimming Pool Contractor License' },
    flooring:         { authority: 'California Contractors State License Board (CSLB)', licenseType: 'C-15 Flooring and Floor Covering Contractor License' },
  },
  CO: {
    electrician:      { authority: 'State Electrical Board of Colorado', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Colorado Department of Regulatory Agencies', licenseType: 'Master Plumber License' },
    pest_control:     { authority: 'Colorado Department of Agriculture', licenseType: 'Pesticide Business License' },
    security_systems: { authority: 'Colorado Department of Regulatory Agencies', licenseType: 'Alarm System Contractor License' },
    locksmith:        { authority: 'Colorado Bureau of Investigation', licenseType: 'Locksmith Registration' },
  },
  CT: {
    electrician:      { authority: 'Connecticut Department of Consumer Protection', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Connecticut Department of Consumer Protection', licenseType: 'Plumbing & Piping Contractor License' },
    hvac:             { authority: 'Connecticut Department of Consumer Protection', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Connecticut Department of Energy & Environmental Protection', licenseType: 'Pesticide Applicator License' },
    security_systems: { authority: 'Connecticut Department of Emergency Services & Public Protection', licenseType: 'Alarm System Installer License' },
    locksmith:        { authority: 'Connecticut Department of Emergency Services & Public Protection', licenseType: 'Locksmith License' },
    roofing:          { authority: 'Connecticut Department of Consumer Protection', licenseType: 'Home Improvement Contractor License' },
  },
  DE: {
    electrician:      { authority: 'Delaware Department of Labor, Division of Industrial Affairs', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Delaware Division of Professional Regulation', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Delaware Division of Professional Regulation', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Delaware Department of Agriculture', licenseType: 'Commercial Pesticide Applicator License' },
    security_systems: { authority: 'Delaware State Police', licenseType: 'Alarm System Contractor License' },
    roofing:          { authority: 'Delaware Division of Revenue', licenseType: 'Contractor License' },
  },
  DC: {
    electrician:      { authority: 'DC Department of Consumer and Regulatory Affairs (DCRA)', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'DC Department of Consumer and Regulatory Affairs (DCRA)', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'DC Department of Consumer and Regulatory Affairs (DCRA)', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'DC Department of Energy and Environment', licenseType: 'Pesticide Operator License' },
    security_systems: { authority: 'DC Department of Consumer and Regulatory Affairs (DCRA)', licenseType: 'Security System Contractor License' },
    locksmith:        { authority: 'DC Department of Consumer and Regulatory Affairs (DCRA)', licenseType: 'Locksmith License' },
    roofing:          { authority: 'DC Department of Consumer and Regulatory Affairs (DCRA)', licenseType: 'General Contractor License' },
  },
  FL: {
    electrician:      { authority: 'Florida Department of Business & Professional Regulation (DBPR)', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Florida Department of Business & Professional Regulation (DBPR)', licenseType: 'Plumbing Contractor License' },
    hvac:             { authority: 'Florida Department of Business & Professional Regulation (DBPR)', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Florida Department of Agriculture and Consumer Services', licenseType: 'Pest Control License' },
    security_systems: { authority: 'Florida Department of Agriculture and Consumer Services', licenseType: 'Alarm System Contractor License' },
    locksmith:        { authority: 'Florida Department of Agriculture and Consumer Services', licenseType: 'Locksmith License' },
    roofing:          { authority: 'Florida Department of Business & Professional Regulation (DBPR)', licenseType: 'Roofing Contractor License' },
    pool_service:     { authority: 'Florida Department of Business & Professional Regulation (DBPR)', licenseType: 'Swimming Pool/Spa Contractor License' },
  },
  GA: {
    electrician:      { authority: 'Georgia State Construction Industry Licensing Board', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Georgia State Construction Industry Licensing Board', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Georgia State Construction Industry Licensing Board', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Georgia Department of Agriculture', licenseType: 'Pest Control License' },
    security_systems: { authority: 'Georgia Secretary of State', licenseType: 'Electronic Security License' },
    roofing:          { authority: 'Georgia State Construction Industry Licensing Board', licenseType: 'General Contractor License' },
  },
  HI: {
    electrician:      { authority: 'Hawaii Contractors License Board', licenseType: 'C-13 Electrical Contractor License' },
    plumber:          { authority: 'Hawaii Contractors License Board', licenseType: 'C-37 Plumbing Contractor License' },
    hvac:             { authority: 'Hawaii Contractors License Board', licenseType: 'C-36 HVAC Contractor License' },
    pest_control:     { authority: 'Hawaii Department of Agriculture', licenseType: 'Pest Control Operator License' },
    security_systems: { authority: 'Hawaii Department of Commerce and Consumer Affairs', licenseType: 'Electronic Security License' },
    roofing:          { authority: 'Hawaii Contractors License Board', licenseType: 'C-42 Roofing Contractor License' },
  },
  ID: {
    electrician:      { authority: 'Idaho Division of Building Safety', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Idaho Division of Building Safety', licenseType: 'Plumbing Contractor License' },
    hvac:             { authority: 'Idaho Division of Building Safety', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Idaho State Department of Agriculture', licenseType: 'Pest Management License' },
    security_systems: { authority: 'Idaho Bureau of Occupational Licenses', licenseType: 'Alarm System Contractor License' },
  },
  IL: {
    plumber:          { authority: 'Illinois Department of Public Health', licenseType: 'Master Plumber License' },
    pest_control:     { authority: 'Illinois Department of Public Health', licenseType: 'Pest Control Operator License' },
    security_systems: { authority: 'Illinois Department of Financial & Professional Regulation', licenseType: 'Alarm Detection System License' },
    locksmith:        { authority: 'Illinois Department of Financial & Professional Regulation', licenseType: 'Locksmith License' },
    electrician:      { authority: 'Local jurisdiction (no statewide license)', licenseType: 'City/County Electrical License', note: 'Illinois does not issue a statewide electrical contractor license. Check with your local city or county.' },
    hvac:             { authority: 'Local jurisdiction (no statewide license)', licenseType: 'City/County HVAC License', note: 'Illinois does not issue a statewide HVAC contractor license. Check with your local city or county.' },
  },
  IN: {
    electrician:      { authority: 'Indiana Fire Prevention & Building Safety Commission', licenseType: 'Electrical Contractor Registration' },
    plumber:          { authority: 'Indiana Plumbing Commission', licenseType: 'Plumbing Contractor License' },
    pest_control:     { authority: 'Indiana Office of Indiana State Chemist', licenseType: 'Pest Control Business License' },
    security_systems: { authority: 'Indiana Professional Licensing Agency', licenseType: 'Alarm System Contractor License' },
    locksmith:        { authority: 'Indiana Professional Licensing Agency', licenseType: 'Locksmith License' },
    roofing:          { authority: 'Indiana Secretary of State', licenseType: 'Contractor Registration' },
  },
  IA: {
    electrician:      { authority: 'Iowa Department of Public Health', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Iowa Plumbing & Mechanical Systems Board', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Iowa Plumbing & Mechanical Systems Board', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Iowa Department of Agriculture and Land Stewardship', licenseType: 'Commercial Pesticide Applicator License' },
  },
  KS: {
    plumber:          { authority: 'Kansas State Board of Technical Professions', licenseType: 'Master Plumber License' },
    pest_control:     { authority: 'Kansas Department of Agriculture', licenseType: 'Pest Management License' },
    electrician:      { authority: 'Local jurisdiction (no statewide license)', licenseType: 'City/County Electrical License', note: 'Kansas does not issue a statewide electrical contractor license. Check with your local city or county.' },
  },
  KY: {
    electrician:      { authority: 'Kentucky State Board of Electricians', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Kentucky State Board of Plumbing', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Kentucky Department of Housing, Buildings & Construction', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Kentucky Department of Agriculture', licenseType: 'Pest Control Business License' },
    security_systems: { authority: 'Kentucky Secretary of State', licenseType: 'Alarm System Contractor License' },
    roofing:          { authority: 'Kentucky Department of Housing, Buildings & Construction', licenseType: 'Contractor License' },
  },
  LA: {
    electrician:      { authority: 'Louisiana State Licensing Board for Contractors (LSLBC)', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Louisiana State Plumbing Board', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Louisiana State Licensing Board for Contractors (LSLBC)', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Louisiana Department of Agriculture & Forestry', licenseType: 'Pest Control Business License' },
    security_systems: { authority: 'Louisiana State Board of Private Security Examiners', licenseType: 'Alarm System Contractor License' },
    locksmith:        { authority: 'Louisiana State Board of Private Security Examiners', licenseType: 'Locksmith License' },
    roofing:          { authority: 'Louisiana State Licensing Board for Contractors (LSLBC)', licenseType: 'General Contractor License' },
  },
  ME: {
    electrician:      { authority: "Maine Electricians' Examining Board", licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Maine State Plumbing Board', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Maine Department of Professional & Financial Regulation', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Maine Board of Pesticides Control', licenseType: 'Pesticide Applicator License' },
    security_systems: { authority: 'Maine Department of Public Safety', licenseType: 'Alarm System Contractor License' },
    locksmith:        { authority: 'Maine Department of Public Safety', licenseType: 'Locksmith License' },
    roofing:          { authority: 'Maine Office of Professional & Occupational Regulation', licenseType: 'Home Construction Contractor Registration' },
  },
  MD: {
    electrician:      { authority: 'Maryland State Board of Master Electricians', licenseType: 'Master Electrician License' },
    plumber:          { authority: 'Maryland Department of Labor', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Maryland Department of Labor', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Maryland Department of Agriculture', licenseType: 'Pesticide Applicator License' },
    security_systems: { authority: 'Maryland Department of Labor', licenseType: 'Security System Contractor License' },
    locksmith:        { authority: 'Maryland Department of Labor', licenseType: 'Locksmith License' },
    roofing:          { authority: 'Maryland Home Improvement Commission', licenseType: 'Home Improvement Contractor License' },
  },
  MA: {
    electrician:      { authority: 'Massachusetts Board of State Examiners of Electricians', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Massachusetts Division of Occupational Licensure', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Massachusetts Division of Occupational Licensure', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Massachusetts Department of Agricultural Resources', licenseType: 'Pesticide Applicator License' },
    security_systems: { authority: 'Massachusetts Department of Public Safety', licenseType: 'Burglar Alarm Installer License' },
    roofing:          { authority: 'Massachusetts Office of Consumer Affairs & Business Regulation', licenseType: 'Home Improvement Contractor Registration' },
  },
  MI: {
    electrician:      { authority: 'Michigan Department of Licensing and Regulatory Affairs (LARA)', licenseType: 'Master Electrician License' },
    plumber:          { authority: 'Michigan Department of Licensing and Regulatory Affairs (LARA)', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Michigan Department of Licensing and Regulatory Affairs (LARA)', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Michigan Department of Agriculture and Rural Development', licenseType: 'Pesticide Business License' },
    security_systems: { authority: 'Michigan Department of Licensing and Regulatory Affairs (LARA)', licenseType: 'Alarm System Contractor License' },
    roofing:          { authority: 'Michigan Department of Licensing and Regulatory Affairs (LARA)', licenseType: 'Residential Builder License' },
  },
  MN: {
    electrician:      { authority: 'Minnesota Department of Labor and Industry', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Minnesota Department of Labor and Industry', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Minnesota Department of Labor and Industry', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Minnesota Department of Agriculture', licenseType: 'Pesticide Applicator License' },
    security_systems: { authority: 'Minnesota Department of Public Safety', licenseType: 'Alarm System Contractor License' },
    roofing:          { authority: 'Minnesota Department of Labor and Industry', licenseType: 'Residential Contractor License' },
  },
  MS: {
    electrician:      { authority: 'Mississippi State Board of Contractors', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Mississippi State Board of Contractors', licenseType: 'Plumbing Contractor License' },
    hvac:             { authority: 'Mississippi State Board of Contractors', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Mississippi Department of Agriculture & Commerce', licenseType: 'Pest Control License' },
    security_systems: { authority: 'Mississippi Department of Public Safety', licenseType: 'Alarm System Contractor License' },
    roofing:          { authority: 'Mississippi State Board of Contractors', licenseType: 'General Contractor License' },
  },
  MO: {
    plumber:          { authority: 'Missouri Division of Professional Registration', licenseType: 'Master Plumber License' },
    pest_control:     { authority: 'Missouri Department of Agriculture', licenseType: 'Pesticide Business License' },
    security_systems: { authority: 'Missouri Department of Public Safety', licenseType: 'Alarm System Contractor License' },
    electrician:      { authority: 'Local jurisdiction (no statewide license)', licenseType: 'City/County Electrical License', note: 'Missouri does not issue a statewide electrical contractor license. Check with your local city or county.' },
    hvac:             { authority: 'Local jurisdiction (no statewide license)', licenseType: 'City/County HVAC License', note: 'Missouri does not issue a statewide HVAC contractor license. Check with your local city or county.' },
  },
  MT: {
    electrician:      { authority: 'Montana Board of Electrical Contractors', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Montana Board of Plumbers', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Montana Department of Labor & Industry', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Montana Department of Agriculture', licenseType: 'Pesticide Applicator License' },
    security_systems: { authority: 'Montana Board of Private Security', licenseType: 'Alarm System Contractor License' },
    roofing:          { authority: 'Montana Department of Labor & Industry', licenseType: 'Contractor Registration' },
  },
  NE: {
    electrician:      { authority: 'Nebraska State Electrical Board', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Nebraska Plumbing Board', licenseType: 'Master Plumber License' },
    pest_control:     { authority: 'Nebraska Department of Agriculture', licenseType: 'Pesticide Business License' },
    security_systems: { authority: 'Nebraska Department of Insurance', licenseType: 'Alarm Company License' },
  },
  NV: {
    electrician:      { authority: 'Nevada State Contractors Board', licenseType: 'C-2 Electrical Contractor License' },
    plumber:          { authority: 'Nevada State Contractors Board', licenseType: 'C-1 Plumbing Contractor License' },
    hvac:             { authority: 'Nevada State Contractors Board', licenseType: 'C-21 HVAC Contractor License' },
    pest_control:     { authority: 'Nevada Department of Agriculture', licenseType: 'Pest Control Operator License' },
    security_systems: { authority: 'Nevada Private Investigators Licensing Board', licenseType: 'Alarm System Contractor License' },
    locksmith:        { authority: 'Nevada Private Investigators Licensing Board', licenseType: 'Locksmith License' },
    roofing:          { authority: 'Nevada State Contractors Board', licenseType: 'C-15 Roofing Contractor License' },
    pool_service:     { authority: 'Nevada State Contractors Board', licenseType: 'C-1a Swimming Pool Contractor License' },
  },
  NH: {
    electrician:      { authority: "New Hampshire Electricians' Licensing Board", licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'New Hampshire Office of Professional Licensure and Certification', licenseType: 'Master Plumber License' },
    hvac:             { authority: "New Hampshire Plumbers' Licensing Board", licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'New Hampshire Department of Agriculture', licenseType: 'Pesticide Applicator License' },
    security_systems: { authority: 'New Hampshire Department of Safety', licenseType: 'Alarm System Contractor License' },
    roofing:          { authority: 'New Hampshire Consumer Protection Bureau', licenseType: 'Contractor Registration' },
  },
  NJ: {
    electrician:      { authority: 'New Jersey Division of Consumer Affairs', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'New Jersey Division of Consumer Affairs', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'New Jersey Division of Consumer Affairs', licenseType: 'HVACR Contractor License' },
    pest_control:     { authority: 'New Jersey Department of Environmental Protection', licenseType: 'Pesticide Operator License' },
    security_systems: { authority: 'New Jersey Division of Consumer Affairs', licenseType: 'Burglar Alarm Business License' },
    locksmith:        { authority: 'New Jersey Division of Consumer Affairs', licenseType: 'Locksmith Registration' },
    roofing:          { authority: 'New Jersey Division of Consumer Affairs', licenseType: 'Home Improvement Contractor License' },
  },
  NM: {
    electrician:      { authority: 'New Mexico Construction Industries Division', licenseType: 'EE-98 Electrical Contractor License' },
    plumber:          { authority: 'New Mexico Construction Industries Division', licenseType: 'PB-98 Plumbing Contractor License' },
    hvac:             { authority: 'New Mexico Construction Industries Division', licenseType: 'MM-98 HVAC Contractor License' },
    pest_control:     { authority: 'New Mexico Department of Agriculture', licenseType: 'Pesticide Business License' },
    security_systems: { authority: 'New Mexico Department of Public Safety', licenseType: 'Alarm System Contractor License' },
    roofing:          { authority: 'New Mexico Construction Industries Division', licenseType: 'GB-98 General Contractor License' },
  },
  NY: {
    pest_control:     { authority: 'New York State Department of Environmental Conservation', licenseType: 'Pesticide Business License' },
    security_systems: { authority: 'New York State Division of Licensing Services', licenseType: 'Security Guard/Alarm Installer License' },
    locksmith:        { authority: 'New York State Division of Licensing Services', licenseType: 'Locksmith License' },
    electrician:      { authority: 'Local jurisdiction (no statewide license)', licenseType: 'City/County Electrical License', note: 'New York does not issue a statewide electrical contractor license. NYC requires a Master Electrician License through the NYC Dept of Buildings.' },
    plumber:          { authority: 'Local jurisdiction (no statewide license)', licenseType: 'City/County Plumber License', note: 'New York does not issue a statewide plumber license. Licensing is handled by local jurisdiction.' },
    hvac:             { authority: 'Local jurisdiction (no statewide license)', licenseType: 'City/County HVAC License', note: 'New York does not issue a statewide HVAC contractor license. Check with your local jurisdiction.' },
    roofing:          { authority: 'New York State Consumer Protection Division', licenseType: 'Home Improvement Contractor License' },
  },
  NC: {
    electrician:      { authority: 'North Carolina State Board of Examiners of Electrical Contractors', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'North Carolina State Board of Plumbing, Heating & Fire Sprinkler Contractors', licenseType: 'Plumbing Contractor License' },
    hvac:             { authority: 'North Carolina State Board of Plumbing, Heating & Fire Sprinkler Contractors', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'North Carolina Department of Agriculture & Consumer Services', licenseType: 'Pest Control License' },
    security_systems: { authority: 'North Carolina Secretary of State', licenseType: 'Alarm System Contractor License' },
    locksmith:        { authority: 'North Carolina Locksmith Licensing Board', licenseType: 'Locksmith License' },
    roofing:          { authority: 'North Carolina Licensing Board for General Contractors', licenseType: 'General Contractor License' },
  },
  ND: {
    electrician:      { authority: 'North Dakota State Electrical Board', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'North Dakota State Plumbing Board', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'North Dakota Department of Labor and Human Rights', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'North Dakota Department of Agriculture', licenseType: 'Pest Management License' },
    roofing:          { authority: 'North Dakota Secretary of State', licenseType: 'Contractor License' },
  },
  OH: {
    electrician:      { authority: 'Ohio Construction Industry Examining Board', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Ohio Construction Industry Examining Board', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Ohio Construction Industry Examining Board', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Ohio Department of Agriculture', licenseType: 'Pest Control Business License' },
    security_systems: { authority: 'Ohio Department of Public Safety', licenseType: 'Alarm System Contractor License' },
    locksmith:        { authority: 'Ohio Department of Commerce', licenseType: 'Locksmith License' },
    roofing:          { authority: 'Ohio Construction Industry Examining Board', licenseType: 'Roofing Contractor License' },
  },
  OK: {
    electrician:      { authority: 'Oklahoma Construction Industries Board', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Oklahoma Construction Industries Board', licenseType: 'Plumbing Contractor License' },
    hvac:             { authority: 'Oklahoma Construction Industries Board', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Oklahoma Department of Agriculture, Food and Forestry', licenseType: 'Pest Control License' },
    security_systems: { authority: 'Oklahoma Council on Law Enforcement Education and Training', licenseType: 'Alarm System Contractor License' },
    roofing:          { authority: 'Oklahoma Construction Industries Board', licenseType: 'General Contractor License' },
  },
  OR: {
    electrician:      { authority: 'Oregon Construction Contractors Board (CCB)', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Oregon Construction Contractors Board (CCB)', licenseType: 'Plumbing Contractor License' },
    hvac:             { authority: 'Oregon Construction Contractors Board (CCB)', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Oregon Department of Agriculture', licenseType: 'Pesticide Consultant/Operator License' },
    security_systems: { authority: 'Oregon Department of Public Safety Standards and Training', licenseType: 'Alarm System Contractor License' },
    locksmith:        { authority: 'Oregon Department of Public Safety Standards and Training', licenseType: 'Locksmith License' },
    roofing:          { authority: 'Oregon Construction Contractors Board (CCB)', licenseType: 'Roofing Contractor License' },
  },
  PA: {
    pest_control:     { authority: 'Pennsylvania Department of Agriculture', licenseType: 'Pesticide Business License' },
    security_systems: { authority: 'Pennsylvania State Police', licenseType: 'Alarm System Contractor License' },
    roofing:          { authority: "Pennsylvania Attorney General's Office", licenseType: 'Home Improvement Contractor Registration' },
    electrician:      { authority: 'Local jurisdiction (no statewide license)', licenseType: 'City/County Electrical License', note: 'Pennsylvania does not issue a statewide electrical contractor license. Check with your local city or county.' },
    plumber:          { authority: 'Local jurisdiction (no statewide license)', licenseType: 'City/County Plumber License', note: 'Pennsylvania does not issue a statewide plumber license. Check with your local city or county.' },
    hvac:             { authority: 'Local jurisdiction (no statewide license)', licenseType: 'City/County HVAC License', note: 'Pennsylvania does not issue a statewide HVAC contractor license. Check with your local city or county.' },
  },
  RI: {
    electrician:      { authority: 'Rhode Island State Board of Electricians', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Rhode Island State Board of Plumbing Examiners', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Rhode Island State Building Code Commission', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Rhode Island Department of Environmental Management', licenseType: 'Pesticide Applicator License' },
    security_systems: { authority: 'Rhode Island Department of Business Regulation', licenseType: 'Burglar Alarm Business License' },
    roofing:          { authority: "Rhode Island Contractors' Registration and Licensing Board", licenseType: 'Contractor Registration' },
  },
  SC: {
    electrician:      { authority: 'South Carolina Contractors Licensing Board', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'South Carolina Contractors Licensing Board', licenseType: 'Plumbing Contractor License' },
    hvac:             { authority: 'South Carolina Contractors Licensing Board', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'South Carolina Department of Pesticide Regulation', licenseType: 'Pest Control Business License' },
    security_systems: { authority: 'South Carolina Law Enforcement Division (SLED)', licenseType: 'Alarm System Contractor License' },
    roofing:          { authority: 'South Carolina Contractors Licensing Board', licenseType: 'Roofing Contractor License' },
  },
  SD: {
    electrician:      { authority: 'South Dakota State Electrical Commission', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'South Dakota State Plumbing Commission', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'South Dakota Department of Labor and Regulation', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'South Dakota Department of Agriculture & Natural Resources', licenseType: 'Commercial Pesticide Applicator License' },
    security_systems: { authority: 'South Dakota Division of Insurance', licenseType: 'Alarm System Contractor License' },
  },
  TN: {
    electrician:      { authority: 'Tennessee Electrical Licensing Board', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: "Tennessee Contractor's Licensing Board", licenseType: 'Plumbing Contractor License' },
    hvac:             { authority: "Tennessee Contractor's Licensing Board", licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Tennessee Department of Agriculture', licenseType: 'Pest Control Business License' },
    security_systems: { authority: 'Tennessee Secretary of State', licenseType: 'Alarm System Contractor License' },
    locksmith:        { authority: 'Tennessee Secretary of State', licenseType: 'Locksmith License' },
    roofing:          { authority: "Tennessee Contractor's Licensing Board", licenseType: 'General Contractor License' },
  },
  TX: {
    electrician:      { authority: 'Texas Department of Licensing and Regulation (TDLR)', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Texas State Board of Plumbing Examiners', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Texas Department of Licensing and Regulation (TDLR)', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Texas Department of Agriculture', licenseType: 'Structural Pest Control License' },
    security_systems: { authority: 'Texas Department of Public Safety', licenseType: 'Alarm System Contractor License' },
    locksmith:        { authority: 'Texas Department of Public Safety', licenseType: 'Locksmith License' },
    pool_service:     { authority: 'Texas Department of Licensing and Regulation (TDLR)', licenseType: 'Swimming Pool/Spa Contractor License' },
  },
  UT: {
    electrician:      { authority: 'Utah Division of Occupational and Professional Licensing (DOPL)', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Utah Division of Occupational and Professional Licensing (DOPL)', licenseType: 'Plumbing Contractor License' },
    hvac:             { authority: 'Utah Division of Occupational and Professional Licensing (DOPL)', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Utah Department of Agriculture and Food', licenseType: 'Commercial Pesticide Applicator License' },
    security_systems: { authority: 'Utah Division of Occupational and Professional Licensing (DOPL)', licenseType: 'Alarm System Contractor License' },
    roofing:          { authority: 'Utah Division of Occupational and Professional Licensing (DOPL)', licenseType: 'General Contractor License' },
  },
  VT: {
    electrician:      { authority: 'Vermont Secretary of State', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Vermont Secretary of State', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Vermont Secretary of State', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Vermont Agency of Agriculture, Food & Markets', licenseType: 'Pesticide Applicator License' },
    security_systems: { authority: 'Vermont Department of Public Safety', licenseType: 'Alarm System Contractor License' },
    roofing:          { authority: 'Vermont Secretary of State', licenseType: 'Contractor Registration' },
  },
  VA: {
    electrician:      { authority: 'Virginia Department of Professional and Occupational Regulation (DPOR)', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Virginia Department of Professional and Occupational Regulation (DPOR)', licenseType: 'Plumbing Contractor License' },
    hvac:             { authority: 'Virginia Department of Professional and Occupational Regulation (DPOR)', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Virginia Department of Agriculture and Consumer Services', licenseType: 'Pest Management Business License' },
    security_systems: { authority: 'Virginia Department of Criminal Justice Services', licenseType: 'Alarm System Contractor License' },
    locksmith:        { authority: 'Virginia Department of Criminal Justice Services', licenseType: 'Locksmith License' },
    roofing:          { authority: 'Virginia Department of Professional and Occupational Regulation (DPOR)', licenseType: 'Class A/B Contractor License' },
  },
  WA: {
    electrician:      { authority: 'Washington State Department of Labor & Industries', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Washington State Department of Labor & Industries', licenseType: 'Plumbing Contractor License' },
    hvac:             { authority: 'Washington State Department of Labor & Industries', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Washington State Department of Agriculture', licenseType: 'Pest Control Operator License' },
    security_systems: { authority: 'Washington State Department of Licensing', licenseType: 'Alarm System Contractor License' },
    locksmith:        { authority: 'Washington State Department of Licensing', licenseType: 'Locksmith Registration' },
    roofing:          { authority: 'Washington State Department of Labor & Industries', licenseType: 'General Contractor License' },
  },
  WV: {
    electrician:      { authority: 'West Virginia Fire Marshal, Electrical Division', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'West Virginia Plumbers Licensing Board', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'West Virginia Division of Labor', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'West Virginia Department of Agriculture', licenseType: 'Pesticide Applicator License' },
    security_systems: { authority: 'West Virginia Secretary of State', licenseType: 'Alarm System Contractor License' },
    roofing:          { authority: 'West Virginia Contractor Licensing Board', licenseType: 'Roofing Contractor License' },
  },
  WI: {
    electrician:      { authority: 'Wisconsin Department of Safety and Professional Services', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Wisconsin Department of Safety and Professional Services', licenseType: 'Master Plumber License' },
    hvac:             { authority: 'Wisconsin Department of Safety and Professional Services', licenseType: 'HVAC Contractor License' },
    pest_control:     { authority: 'Wisconsin Department of Agriculture, Trade and Consumer Protection', licenseType: 'Pesticide Business License' },
    security_systems: { authority: 'Wisconsin Department of Safety and Professional Services', licenseType: 'Alarm System Contractor License' },
    roofing:          { authority: 'Wisconsin Department of Safety and Professional Services', licenseType: 'Dwelling Contractor License' },
  },
  WY: {
    electrician:      { authority: 'Wyoming Electrical Board', licenseType: 'Electrical Contractor License' },
    plumber:          { authority: 'Wyoming Board of Plumbers', licenseType: 'Master Plumber License' },
    pest_control:     { authority: 'Wyoming Department of Agriculture', licenseType: 'Pesticide Operator License' },
  },
}

// Returns license info for a given state + category, or null if no state license required
export function getLicenseInfo(stateCode: string, categorySlug: string): LicenseInfo | null {
  return STATE_LICENSE_INFO[stateCode]?.[categorySlug] ?? null
}

// Returns true if the category requires a license in ANY state (always show license fields)
export const LICENSED_CATEGORIES = new Set([
  'electrician', 'plumber', 'hvac', 'pest_control', 'security_systems',
  'locksmith', 'roofing', 'pool_service',
])

// Returns true if the category should always carry liability insurance
export const INSURED_CATEGORIES = new Set([
  'electrician', 'plumber', 'hvac', 'pest_control', 'security_systems',
  'locksmith', 'roofing', 'pool_service', 'carpenter', 'handyman',
  'moving', 'appliance_repair', 'garage_door', 'painter',
  'flooring', 'tiling', 'landscaper', 'mobile_mechanic',
  'auto_glass', 'towing', 'auto_painting',
])
